#!/usr/bin/env python3

import requests, argparse, sys

from scraper.page_processor import PageProcessor
from scraper.article_scraper import GoogleScraper
from nlp.nlp import NLProcessor

from definitions import NEGATIVE_QUERIES

if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="scraper")
    parser.add_argument("-n", "--narticles", type=int, action="store", default=0)
    args = parser.parse_args()
    if args.narticles <= 0:
        print("Sorry, values <= 0 are not valid numbers for articles to be scraped\nExiting")
        sys.exit(1)
    if len(NEGATIVE_QUERIES) == 0:
        print("No negative queries have been supplied in .env\nExiting")
        sys.exit(1)
    from database.mock_database import DatabaseNegative

    for query in NEGATIVE_QUERIES:
        print(f"scraping for query [{query}]")
        urls = GoogleScraper.find_news_urls_for_query(query, args.narticles)
        print(f"scraped {len(urls)} urls for query")
        for url in urls:
            print(f"\r\033[Krequesting url [{url}]", end="")
            page = requests.get(url).text
            processor = PageProcessor(page)
            summarization = "".join(NLProcessor.summarize(processor.get_fulltext()))
            DatabaseNegative.insert((url, summarization, query))
    print("\nDONE")
    GoogleScraper.quit()
